### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by lolisa** [feisuzhu/thbattle#96]
marisa@lolisa:~/Work/thbattle$ buildout -vvv
Traceback (most recent call last):
  File "/usr/local/bin/buildout", line 9, in <module>
    load_entry_point('zc.buildout==2.3.1', 'console_scripts', 'buildout')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 356, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2476, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2190, in load
    ['__name__'])
  File "/usr/local/lib/python2.7/dist-packages/zc/buildout/buildout.py", line 18, in <module>
    import zc.buildout.easy_install
  File "/usr/local/lib/python2.7/dist-packages/zc/buildout/easy_install.py", line 29, in <module>
    import setuptools.archive_util
  File "/usr/local/lib/python2.7/dist-packages/setuptools/__init__.py", line 11, in <module>
    from setuptools.extension import Extension
  File "/usr/local/lib/python2.7/dist-packages/setuptools/extension.py", line 8, in <module>
    from .dist import _get_unpatched
  File "/usr/local/lib/python2.7/dist-packages/setuptools/dist.py", line 21, in <module>
    packaging = pkg_resources.packaging
AttributeError: 'module' object has no attribute 'packaging'

**Comment by lolisa** [comment]
debian testing

**Comment by lolisa** [comment]
Downgrade buildout, work.
