### ISSUE TITLE
unable to run

### ISSUE THREAD

**Issue by lolisa** [feisuzhu/thbattle#97]
marisa@lolisa:~/Work/thbattle/bin$ python start_client
/home/marisa/Work/thbattle/src/pyglet/gl/gl_info.py:166: UserWarning: No GL context created yet.
  warnings.warn('No GL context created yet.')
'/home/marisa/Work/thbattle/src'
Traceback (most recent call last):
  File "/home/marisa/Work/thbattle/src/client/core/executive.py", line 365, in do_update
    for p in up.update():
  File "/home/marisa/Work/thbattle/src/autoupdate.py", line 30, in update
    repo = pygit2.Repository(self.base)
  File "/usr/local/lib/python2.7/dist-packages/pygit2/repository.py", line 59, in __init__
    super(Repository, self).__init__(*args, **kwargs)
KeyError: '/home/marisa/Work/thbattle/src'
Traceback (most recent call last):
  File "/home/marisa/Work/thbattle/eggs/gevent-1.0.1-py2.7-linux-x86_64.egg/gevent/greenlet.py", line 327, in run
    result = self._run(*self.args, **self.kwargs)
  File "/home/marisa/Work/thbattle/src/client/ui/screens.py", line 411, in work
    if not options.no_update and not Executive.is_version_match(server['branch']):
  File "/home/marisa/Work/thbattle/src/client/core/executive.py", line 390, in is_version_match
    return up.is_version_match(version)
  File "/home/marisa/Work/thbattle/src/autoupdate.py", line 89, in is_version_match
    repo = pygit2.Repository(self.base)
  File "/usr/local/lib/python2.7/dist-packages/pygit2/repository.py", line 59, in __init__
    super(Repository, self).__init__(*args, **kwargs)
KeyError: '/home/marisa/Work/thbattle/src'
<Greenlet at 0x7f42ecf5a0f0: work> failed with KeyError

Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
AL lib: (EE) alc_cleanup: 1 device not closed
Segmentation fault

I'm on debian.

**Comment by feisuzhu** [comment]
$ start_client --no-update

This will disable auto update, which requires cwd to be a git repo.

**Comment by lolisa** [comment]
All is well.
